### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mcast** [wardi/jsonlines#11]
Link in https://github.com/wardi/jsonlines/blob/gh-pages/on_the_web/index.html is broken...
The site hosting http://trephine.org/t/index.php?title=Newline_delimited_JSON seems to have lapsed, currently it is serving a placeholder.
The last archive copy of it is at http://web.archive.org/web/20141009224232/http://trephine.org/t/index.php?title=Newline_delimited_JSON

Thanks for the useful jsonl tips,

Matthew

**Comment by hugovk** [comment]
@mcast How about a PR?

**Comment by is2ei** [comment]
It seems this is fixed in https://github.com/wardi/jsonlines/commit/e07fec0ea4c9d7f3dd171c49ac3fae20520fca71
