### ISSUE TITLE
Newlines in data

### ISSUE THREAD

**Issue by britishtea** [wardi/jsonlines#13]
How are new lines in the data itself handled? Are they illegal?

It would be good to mention this.

**Comment by wardi** [comment]
sure, please send a pull request with suggested text.

Putting a real new line (not a \n in a string) will split the json across multiple lines, each line won't be valid JSON so rule 2 will be broken. I'm fine with making that explicit though.

**Comment by britishtea** [comment]
Are there markdown source files somewhere or should the HTML be altered directly?

**Comment by wardi** [comment]
All I have is the HTML I'm afraid :-(

Also happy to accept PRs that fix that problem
