### ISSUE TITLE
Mention Scrapy

### ISSUE THREAD

**Issue by kmike** [wardi/jsonlines#14]
[Scrapy ](https://github.com/scrapy/scrapy) is a long-time JSON lines user; this is a default export format since forever. See also: https://twitter.com/pablohoffman/status/547385799093022723 :) 

As a data point, Scrapy uses .jl extenson for JSON lines.

**Comment by wardi** [comment]
Sure, can you send a pull request to modify the " on the web " page?

I started with .jl too, but the conflict with the Julia programming language convinced me to switch to something else.
