### ISSUE TITLE
Spark's use of JSONL

### ISSUE THREAD

**Issue by sigram** [wardi/jsonlines#20]
Apache Spark (http://spark.apache.org) uses JSONL for reading and writing JSON data with `DataFrameReader.json(String path)` and `DataFrameWriter.json(String path)`.

**Comment by hugovk** [comment]
@sigram How about a PR?

**Comment by DanielArthurUK** [comment]
@hugovk @sigram I have opened a PR that includes Apache Spark's use of JSONL 🎉
