### ISSUE TITLE
SSL Error on Firefox

### ISSUE THREAD

**Issue by aphedges** [wardi/jsonlines#37]
In Firefox 75, I get an `SSL_ERROR_BAD_CERT_DOMAIN` because `The certificate is only valid for the following names: *.github.com, github.com`. The certificate should be replaced with a proper one to prevent SSL errors.

**Comment by abeMedia** [comment]
Using cloudflare could fix this with minimal effort.

**Comment by wardi** [comment]
@abeMedia is that the easiest way to serve github pages over https?

**Comment by abeMedia** [comment]
Pretty much. I wrote a blog post on how to do this years ago: https://abemedia.co.uk/blog/tutorials/speed-up-your-github-pages-website-with-cloudflare

**Comment by aphedges** [comment]
I am no longer getting this error, and I confirm that the certificate now matches the domain.
