### ISSUE TITLE
Reference mongodb

### ISSUE THREAD

**Issue by jeroen** [wardi/jsonlines#4]
The popular mongodb uses jsonlines to import/export (potentially large) data: http://docs.mongodb.org/manual/reference/program/mongoexport/#cmdoption--query

**Comment by slang800** [comment]
:-1: - mongo uses BSON internally, and ["MongoDB Extended JSON"](http://docs.mongodb.org/manual/reference/mongodb-extended-json/) for exports... only in strict mode is it valid JSON.

**Comment by sp4ce** [comment]
Yes, unfortunately, they don't reference the format explicitly in their documentation. I will close this issue, please let me know if you have concerns.
