### ISSUE TITLE
Examples are very hard to read

### ISSUE THREAD

**Issue by sigzero** [wardi/jsonlines#51]
The examples have red on black. Very hard to read. Either just use HTML formatting or change the theme for the pictures. Please.

**Comment by hashbackup** [comment]
The whole site is hard to read, especially for people with eyes older than 20.  I know that designers think low-contrast text is somehow a good thing and aesthetically pleasing, but from a practical point of view, they're wrong.

**Comment by wardi** [comment]
I agree. PRs welcome.

**Comment by wardi** [comment]
@sp4ce go for it. The site is html at the moment so there is no deployment process other than pushing changes.
