### ISSUE TITLE
Suggestion for On the Web Page

### ISSUE THREAD

**Issue by atensoftware** [wardi/jsonlines#55]
I suggest to add Shopify's GraphQL Bulk API as example on the web that uses JSONL:
https://shopify.dev/api/usage/bulk-operations/queries

Sometimes the most brilliant ideas are the simplest.  As someone who works with huge data files on a daily basis, I appreciate you creating and popularizing JSONL!

**Comment by wardi** [comment]
Can't take credit for creation, it's too obvious a format. @atensoftware would you like to submit a PR?
