### ISSUE TITLE
CSS HTML Validator v22.0211 supports JSON Lines syntax checking

### ISSUE THREAD

**Issue by AlbertWiersch** [wardi/jsonlines#59]
For page:
https://jsonlines.org/on_the_web/

Please add that CSS HTML Validator for Windows v22.0211+ ( https://www.htmlvalidator.com/ ) now supports JSON Lines syntax checking.

**Comment by wardi** [comment]
sure, submit a PR and I will merge it https://github.com/wardi/jsonlines/blob/gh-pages/on_the_web/index.html

**Comment by AlbertWiersch** [comment]
Thank you!
