### ISSUE TITLE
mention the "jq" tool

### ISSUE THREAD

**Issue by wbolster** [wardi/jsonlines#6]
Instead of the magic Python hack as an alias, the example page should probably recommend using the "identifiy transform" operator `.` offered by `jq` (http://stedolan.github.io/jq/). This will produce nicely formatted JSON (even with colours if stdout is a tty) from a jsonlines file:

```
$ cat data.jsonl | jq .
```

Or even:

```
$ jq . data.jsonl
```

**Comment by wardi** [comment]
@wbolster ah, that's much better. Care to submit a pull request?

**Comment by wardi** [comment]
Hmm, this isn't working for me.

```bash
jq . <<END
{"hi":"there"}
{"how":"areyou"}
END
```

```json
{
  "hi": "there"
}
{
  "how": "areyou"
}
```

**Comment by wardi** [comment]
sorry, I thought we were talking about a conversion thing please disregard

**Comment by wardi** [comment]
fixed in 35ccb

**Comment by wbolster** [comment]
Awesome, you beat me to it.
