### ISSUE TITLE
jsonlines.org down?

### ISSUE THREAD

**Issue by e-minguez** [wardi/jsonlines#62]
According to https://downforeveryoneorjustme.com/jsonlines.org or https://isitdownorjust.me/jsonlines-org/ it is 😭

**Comment by wardi** [comment]
github pages refused to generate a cert  :thinking:  so I've moved the site to cloudflare.

**Comment by e-minguez** [comment]
Thanks!, I'd say you can use this https://uptimerobot.com/ or a similar tool to monitor the status just in case :)

**Comment by wardi** [comment]
I wasn't expecting to need uptimerobot for a github pages hosted site, but that's a good idea
