### ISSUE TITLE
Wrong claims about NDJSON on "On the web" page

### ISSUE THREAD

**Issue by hattesen** [wardi/jsonlines#66]
On the [On the web](https://jsonlines.org/on_the_web/) page, the following entries are listed:

| [NDJ](https://github.com/ndjson/ndjson-spec) is a similar format that also allows C++ style comments and blank lines
| [ndjson](https://github.com/ndjson/ndjson-spec) is a similar format that also allows blank lines

Both of the above entries refer to the same URL.

The first entry has two issues:
1. The formal name, i is NDJSON (uppercase), not NDJ.
2. I see no evidence of _"C++ style comments"_ being supported in the [NDJSON spec](https://github.com/ndjson/ndjson-spec)

**Comment by wardi** [comment]
fixed by a750f07067435e40becc5fab91bb4c61fd638156 thanks!
