### ISSUE TITLE
Mattermost uses jsonl

### ISSUE THREAD

**Issue by emerikaji** [wardi/jsonlines#79]
FYI: Self-hosted Mattermost uses jsonl to [bulk load data](https://docs.mattermost.com/onboard/bulk-loading-data.html), for example in data migration from another instance or other platforms.

Adding this to the On the web page would be nice, especially since Mattermost is a widely-used tool- This could bring some more attention to JSON Lines.

**Comment by wardi** [comment]
sounds good @nishyda care to submit a PR?
