### ISSUE TITLE
bad example

### ISSUE THREAD

**Issue by nathanneuro** [wardi/jsonlines#89]
I think presenting an example of jsonlines where you have a 'technically acceptable' example of a csv style jsonlines is a bad idea.
The main advantage of jsonlines is that each line is independent, there is no 'special first line'. So you can split the file, or read a stream, and have it still make sense.
If you have the first line be 'column names', and every line after that be a list of column values, you've given up the main advantage of using jsonlines. Since that's an edge case which is a bad use of jsonlines, seems incorrect to have it as an example on a site trying to explain to people how to use jsonlines.

["Name", "Session", "Score", "Completed"]
["Gilbert", "2013", 24, true]
["Alexa", "2013", 29, true]
["May", "2012B", 14, false]
["Deloise", "2012A", 19, true]

**Comment by wardi** [comment]
It's a good point. PRs welcome.

**Comment by wardi** [comment]
fixed by #94
