### ISSUE TITLE
What is the appropriate mime-type?

### ISSUE THREAD

**Issue by goloroden** [wardi/jsonlines#9]
What is the appropriate mime-type for jsonlines? Is it `application/json`, too, or should I use something different?

**Comment by webwurst** [comment]
I would also like to see a suggestion :)

**Comment by kmike** [comment]
At ScrapingHub we're using `application/x-jsonlines`.

**Comment by wardi** [comment]
ndjson is now essentially the same format, why not use theirs "application/x-ndjson" https://github.com/ndjson/ndjson-spec

**Comment by giorgiosironi** [comment]
FWIW `application/json` is incorrect, because multiple lines of JSON values are not valid JSON.

**Comment by goloroden** [comment]
Today, almost four years later, I found my own question via Google 😂 

I am going to use `application/x-ndjson`, as @wardi suggested 😊

**Comment by AndreCAndersen** [comment]
I found this issue after giving a suggestion elsewhere: https://github.com/wardi/jsonlines/issues/36

https://tools.ietf.org/html/rfc7464 seems to suggest using `application/json-seq` as the mime type.

**Comment by dimaqq** [comment]
`json-seq` has slightly different format than `jsonl` Orz

**Comment by whlavina** [comment]
The lack of a definitive  IANA Media Type for JSON Lines causes some difficulty for those of us using the format. In the interest of pushing the issue, I took the liberty of starting a conversation:
https://mailarchive.ietf.org/arch/msg/json/dWMWD0JDa2HiUYjWjLjrQExeIx4/

Perhaps someone here would like to join that thread?

Disclaimer: I am in no way affiliated with the IANA/IETF. I am merely interested in using the format, correctly.

**Comment by sthagen** [comment]
> ndjson is now essentially the same format, why not use theirs "application/x-ndjson" https://github.com/ndjson/ndjson-spec

@whlavina - I joined (and was present during the JSON sequences RFC shaping) and I still think `application/x-ndjson` is a sensitive way to go.

**Comment by dimaqq** [comment]
I've also subscribed to the IETF mailing list, but I'm not sure how to respond to a past thread...

Meanwhile, on my end, we support `application/jsonl` and `application/json-lines` MIME types.
