### ISSUE TITLE
Headers on first line?

### ISSUE THREAD

**Issue by ben-white-openx** [wardi/jsonlines#93]
https://jsonlines.org/examples/ gives this example:

```
["Name", "Session", "Score", "Completed"]
["Gilbert", "2013", 24, true]
["Alexa", "2013", 29, true]
["May", "2012B", 14, false]
["Deloise", "2012A", 19, true] 
```

Which I assume is meant to be interpreted as the following JSON objects:
```
{"Name": "Gilbert", "Session": "2013", "Score": 24, "Completed": true}
...
```

But this doesn't seem to be supported by most of the implementations listed on https://jsonlines.org/on_the_web/ - they mostly assume the newline-delimited object format (like the second example on https://jsonlines.org/examples/).  Are implementations meant to interpret the file the way I show it above?

**Comment by wardi** [comment]
There's no implied object interpretation in the first example. In json lines this would be loaded the same as a CSV file: an array of arrays. Any custom interpretation of header line(s) would be up to the specific application.

I included it as an example of a naive light-weight conversion from CSV that can't fail.

Maybe we could add an example after the first showing how this data could be represented as objects without the need for a header line and extra interpretation in the application.

**Comment by wardi** [comment]
Would you like to submit a PR with a second example including the first example data converted to objects and some text suggesting that this is often a better way to represent the same data for the reasons you give?

**Comment by ben-white-openx** [comment]
Sure! I'll add it to #94
